plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

remote_theme: ucsb-cs-course-repos/course-repo-jekyll-theme

suppress_footer: true

name: "CS 8 Winter 2020"
github_url: https://github.com/ucsb-cs8/w20
baseurl: "/w20"
url: "https://ucsb-cs8.github.io/w20"
slides_url: ""

instances:
  -
    instructor: "Kharitonova"
    site_url: "https://ucsb-cs8.github.io/w20"
    github_org:
       name: ucsb-cs8/w20
       url: https://github.com/ucsb-cs8/w20
    piazza_url:  https://piazza.com/class/
    gradescope_url: https://www.gradescope.com


start_week: 1
start_date: 2020-01-05 00:00:00.00-8:00 # Has to start on a Sunday
num_weeks: 10
extra_exam_week: true
lecture_days_of_week: TR

cal_dates: >                                                                    
  [                                                                            
    {"label":"W20 begins", "date":"2020-01-06" },              
    {"label":"Univ Holiday", "date":"2020-01-20" },                            
    {"label":"Univ Holiday", "date":"2020-02-17" },                            
    {"label":"Drop w/o W", "date":"2020-02-03" },                            
    {"label":"DST starts", "date":"2020-03-08" },                            
    {"label":"Classes end", "date":"2020-03-13" },                    
    {"label":"W20 finals start", "date":"2020-03-14" },                        
    {"label":"W20 finals end", "date":"2020-03-20" },                          
    {"label":"W20 qtr ends", "date":"2020-03-20" }                              
  ] 

future: false

course: "CS 8"
qtr: "W20"
quarter: "Winter 2020"

kramdown:
  parse_block_html: false

exclude: ['vendor', 'setup.sh', 'jekyll.sh']
include:
  - _pages

timezone: America/Los_Angeles

collections:
  hwk:
    output: true
    permalink: /hwk/:path/
    last_before: false
  lab:
    output: true
    permalink: /lab/:path/
    last_before: false
  exam:
    output: true
    permalink: /exam/:path/
  info:
    output: true
    permalink: /info/:path/
  lectures:
    output: true
    permalink: /lectures/:path/
  bios:
    output: true
    permalink: /bios/:path

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: default
  -
    scope:
      path: ""
      type: hwk
    values:
      layout: hwk
  -
    scope:
      path: ""
      type: lab
    values:
      layout: lab
  -
    scope:
      path: ""
      type: exam
    values:
      layout: exam_info
  -
    scope:
      path: ""
      type: info
    values:
      layout: info
  -
    scope:
      path: ""
      type: lectures
    values:
      layout: lecture
  -
    scope:
      path: "syllabus.md"
      type: info
    values:
      layout: handout
  -
    scope:
     path: ""
     type: bios
    values:
     layout: default #bio
